package covia.adapter;

import java.util.concurrent.CompletableFuture;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import convex.core.data.ACell;
import convex.core.data.AMap;
import convex.core.data.AString;
import convex.core.data.Maps;
import convex.core.data.Strings;
import convex.core.lang.RT;
import covia.venue.RequestContext;

/**
 * Health Vault adapter — thin wrapper over {@link DLFSAdapter} that
 * hardcodes the drive name to {@code "health-vault"}.
 *
 * <p>Provides {@code vault:read}, {@code vault:write}, {@code vault:list},
 * {@code vault:mkdir}, and {@code vault:delete} operations. The user never
 * needs to specify a drive name — it's always their personal health vault.</p>
 *
 * <p>The {@code health-vault} drive is created automatically on first access
 * (DLFS.connect initialises an empty tree if absent). The user's DLFS_KEY
 * is auto-generated by the underlying DLFSAdapter.</p>
 */
public class VaultAdapter extends AAdapter {

	private static final Logger log = LoggerFactory.getLogger(VaultAdapter.class);

	private static final String ASSETS_PATH = "/adapters/vault/";
	private static final AString DRIVE_NAME = Strings.intern("health-vault");
	private static final AString FIELD_DRIVE = Strings.intern("drive");

	@Override
	public String getName() {
		return "vault";
	}

	@Override
	public String getDescription() {
		return "Personal health vault — read and write files in the user's private health-vault DLFS drive. " +
			   "Stores health documents, lab results, and records with self-sovereign encryption. " +
			   "No drive name needed — always operates on the user's own health vault.";
	}

	@Override
	protected void installAssets() {
		installAsset("vault/read",   ASSETS_PATH + "read.json");
		installAsset("vault/write",  ASSETS_PATH + "write.json");
		installAsset("vault/list",   ASSETS_PATH + "list.json");
		installAsset("vault/mkdir",  ASSETS_PATH + "mkdir.json");
		installAsset("vault/delete", ASSETS_PATH + "delete.json");
		log.info("Vault adapter installed with {} operations", pendingCatalogEntries.size());
	}

	private static final AString OP_KEY = Strings.intern("operation");
	private static final AString ADAPTER_KEY = Strings.intern("adapter");

	@Override
	public CompletableFuture<ACell> invokeFuture(RequestContext ctx, AMap<AString, ACell> meta, ACell input) {
		// Map vault:X → dlfs:X with drive injected
		String subOp = getSubOperation(meta);
		if (subOp == null) {
			return CompletableFuture.failedFuture(new IllegalArgumentException("No vault operation specified"));
		}

		// Inject drive name into input
		AMap<AString, ACell> inputMap = RT.ensureMap(input);
		if (inputMap == null) inputMap = Maps.empty();
		inputMap = inputMap.assoc(FIELD_DRIVE, DRIVE_NAME);

		// Delegate to DLFS adapter with synthetic dlfs:X metadata
		DLFSAdapter dlfs = (DLFSAdapter) engine.getAdapter("dlfs");
		if (dlfs == null) {
			return CompletableFuture.failedFuture(new IllegalStateException("DLFS adapter not available"));
		}

		// Build minimal metadata so DLFSAdapter.getSubOperation() resolves correctly
		AMap<AString, ACell> dlfsMeta = Maps.of(
			OP_KEY, Maps.of(ADAPTER_KEY, Strings.create("dlfs:" + subOp))
		);

		return dlfs.invokeFuture(ctx, dlfsMeta, inputMap);
	}
}
