package covia.adapter;

import java.util.concurrent.CompletableFuture;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import convex.core.data.ACell;
import convex.core.data.AMap;
import convex.core.data.AString;
import convex.core.data.Maps;
import convex.core.data.Strings;
import convex.core.lang.RT;
import covia.venue.RequestContext;

/**
 * Personal vault adapter — thin wrapper over {@link DLFSAdapter} that binds
 * operations to one configured drive. The default drive name is {@code vault};
 * operators can override it with {@code adapters.vault.drive}.
 *
 * <p>Provides {@code vault:read}, {@code vault:write}, {@code vault:list},
 * {@code vault:mkdir}, and {@code vault:delete} operations. The user never
 * needs to specify a drive name — operations always target their personal
 * vault.</p>
 *
 * <p>The {@code vault} drive is created automatically on first access
 * (DLFS.connect initialises an empty tree if absent). The user's DLFS_KEY
 * is auto-generated by the underlying DLFSAdapter.</p>
 */
public class VaultAdapter extends AAdapter {

	private static final Logger log = LoggerFactory.getLogger(VaultAdapter.class);

	private static final String ASSETS_PATH = "/adapters/vault/";
	private static final AString DEFAULT_DRIVE_NAME = Strings.intern("vault");
	private static final AString CONFIG_DRIVE = Strings.intern("drive");
	private static final AString FIELD_DRIVE = Strings.intern("drive");
	private AString driveName = DEFAULT_DRIVE_NAME;

	@Override
	public String getName() {
		return "vault";
	}

	/** Public settings: drive — plain operating parameters, nothing an operator would keep private. */
	@Override
	public AMap<AString, ACell> publicConfig() {
		return publicConfig("drive");
	}

	@Override
	public String getDescription() {
		return "Personal vault — read and write files in the user's configured '" + driveName
			   + "' DLFS drive. " +
			   "Stores documents and application data with self-sovereign integrity. " +
			   "No drive name is needed on individual operations.";
	}

	@Override
	protected void installAssets() {
		AMap<AString, ACell> config = engine.adapterConfig(getName());
		if (config.containsKey(CONFIG_DRIVE)) {
			AString configured = RT.ensureString(config.get(CONFIG_DRIVE));
			if (configured == null || !isValidDriveName(configured.toString())) {
				throw new IllegalStateException("adapters.vault.drive must be a non-empty "
					+ "DLFS drive name without '/', '\\', or ':'");
			}
			driveName = configured;
		}
		if (!engine.config().hasEncryptedEtchPolicy()) {
			log.warn("Vault adapter is enabled for DLFS drive '{}' but this venue does "
				+ "not declare an encrypted Etch policy. Vault contents may be stored "
				+ "unencrypted; configure etch.cipher and key management for sensitive data.",
				driveName);
		}
		installAsset("vault/read",   ASSETS_PATH + "read.json");
		installAsset("vault/write",  ASSETS_PATH + "write.json");
		installAsset("vault/list",   ASSETS_PATH + "list.json");
		installAsset("vault/mkdir",  ASSETS_PATH + "mkdir.json");
		installAsset("vault/delete", ASSETS_PATH + "delete.json");
		log.info("Vault adapter installed with {} operations", pendingCatalogEntries.size());
	}

	private static boolean isValidDriveName(String name) {
		return name != null && !name.isBlank()
			&& name.indexOf('/') < 0 && name.indexOf('\\') < 0 && name.indexOf(':') < 0;
	}

	@Override
	public CompletableFuture<ACell> invokeFuture(RequestContext ctx, AMap<AString, ACell> meta, ACell input) {
		// Map vault:X → dlfs:X with drive injected
		String subOp = getSubOperation(meta);
		if (subOp == null) {
			return CompletableFuture.failedFuture(new IllegalArgumentException("No vault operation specified"));
		}

		// Inject drive name into input
		AMap<AString, ACell> inputMap = RT.castMap(input);
		if (inputMap == null) inputMap = Maps.empty();
		inputMap = inputMap.assoc(FIELD_DRIVE, driveName);

		// Delegate to the typed DLFS operation boundary.
		DLFSAdapter dlfs = (DLFSAdapter) engine.getAdapter("dlfs");
		if (dlfs == null) {
			return CompletableFuture.failedFuture(new IllegalStateException("DLFS adapter not available"));
		}

		return dlfs.invokeBoundOperation(ctx, subOp, inputMap);
	}
}
